#include "usb_cdc_handler.h"
#include "usbd_cdc_if.h"   /* CDC_Transmit_FS(), USBD_OK – generated by CubeMX */
#include <string.h>

/* Power-of-two ring buffer for bytes received from the host */
#define RX_BUF_SIZE 256U   /* must be power-of-two */
#define RX_BUF_MASK (RX_BUF_SIZE - 1U)

static struct {
    uint8_t          buf[RX_BUF_SIZE];
    volatile uint16_t head;   /* written by USB ISR  */
    volatile uint16_t tail;   /* read by main loop   */
} rx;

static volatile uint8_t new_connection_flag = 0;
static volatile uint8_t tx_dead = 0;   /* set when TX endpoint is stuck; cleared on reconnect */

void CDC_Handler_Init(void)
{
    rx.head = 0;
    rx.tail = 0;
}

/* Called from CDC_SET_CONTROL_LINE_STATE – ISR-safe */
void CDC_Handler_SetConnected(void)
{
    rx.head = rx.tail = 0;   /* flush any stale RX from previous session */
    tx_dead = 0;             /* un-gate writes on reconnect */
    new_connection_flag = 1;
}

bool CDC_Handler_NewConnection(void)
{
    if (!new_connection_flag) return false;
    new_connection_flag = 0;
    return true;
}

/* Called from CDC_Receive_FS() inside usbd_cdc_if.c (see USER CODE section) */
void CDC_Handler_RxCallback(const uint8_t *data, uint32_t len)
{
    for (uint32_t i = 0; i < len; i++)
    {
        uint16_t next = (rx.head + 1U) & RX_BUF_MASK;
        if (next != rx.tail)   /* drop silently if full */
        {
            rx.buf[rx.head] = data[i];
            rx.head = next;
        }
    }
}

int CDC_Handler_GetChar(void)
{
    if (rx.head == rx.tail) return -1;
    uint8_t c  = rx.buf[rx.tail];
    rx.tail    = (rx.tail + 1U) & RX_BUF_MASK;
    return (int)c;
}

int CDC_Handler_Write(const uint8_t *data, uint16_t len)
{
    if (tx_dead) return -1;

    /* Retry until the IN endpoint is free or the link is declared dead.
     * TxState can legitimately stay busy for one full USB frame (~1 ms),
     * so 100 ms covers any realistic burst without blocking forever.
     * If it never clears, a USB glitch has stuck TxState — mark dead so
     * callers don't keep hammering a broken pipe until reconnect fires. */
    uint32_t t0 = HAL_GetTick();
    while (CDC_Transmit_FS((uint8_t *)data, len) != USBD_OK)
    {
        if ((HAL_GetTick() - t0) >= 100U)
        {
            tx_dead = 1;
            return -1;
        }
        HAL_Delay(1);
    }
    return 0;
}

int CDC_Handler_WriteStr(const char *str)
{
    return CDC_Handler_Write((const uint8_t *)str, (uint16_t)strlen(str));
}
